//
//  ParseStudentLocation.swift
//  OnTheMap
//
//  Created by zenkiu on 11/24/16.
//  Copyright © 2016 zenkiu. All rights reserved.
//



struct ParseStudentLocation {
    
    let objectId : String? //an auto-generated id/key generated by Parse which uniquely identifies a StudentLocation (Sample: 8ZExGR5uX8)
    
    let uniqueKey : String? // an extra (optional) key used to uniquely identify a StudentLocation; you should populate this value using your Udacity account id (Sample 1234)
    
    let firstName : String? //the first name of the student which matches their Udacity profile first name (Sample: John)
    
    let lastName : String? //the last name of the student which matches their Udacity profile last name (Sample: Doe )
    
    let mapString : String? //the location string used for geocoding the student location (Sample : Mountain View, CA)
    
    
    let createdAt : String? // the date when the student location was created
    
    
    
    let mediaURL : String? //the URL provided by the student
    
    let latitude : Double? //the latitude of the student location (ranges from -90 to 90) (37.386052)
    
    let longitude : Double? //the longitude of the student location (ranges from -180 to 180) (Sample: -122.083851)
    
    /*
    let updatedAt : String // the date when the student location was last updated
    
    let ACL : String  //  the Parse access and control list (ACL), i.e. permissions, for this StudentLocation entry (Sample: Public Read and Write)
    
    
 */
 
    // construct a UdacityStudent from a dictionary
    init(dictionary: [String:AnyObject]) {
        
        
        createdAt = dictionary[ParseStudentLocationClient.JSONResponseKeys.CreateAt] as?  String

        firstName = dictionary[ParseStudentLocationClient.JSONResponseKeys.FirstName] as?  String
        
        lastName = dictionary[ParseStudentLocationClient.JSONResponseKeys.LastName] as?  String
        
        objectId = dictionary[ParseStudentLocationClient.JSONResponseKeys.ObjectId] as?  String
        
        uniqueKey = dictionary[ParseStudentLocationClient.JSONResponseKeys.UniqueKey] as?  String
        
        mapString = dictionary[ParseStudentLocationClient.JSONResponseKeys.MapString] as?  String
        
        mediaURL = dictionary[ParseStudentLocationClient.JSONResponseKeys.MediaURL] as? String
        
        latitude = dictionary[ParseStudentLocationClient.JSONResponseKeys.Latitude] as?  Double
        
        longitude = dictionary[ParseStudentLocationClient.JSONResponseKeys.Longitude] as?  Double
        
        
    }

}


    
